### ISSUE TITLE
Origin mention in the Privacy and Security section

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/audiobooks#22]
> In an audiobook manifest, all remote resources should share the same origin as the manifest file where possible.
https://www.w3.org/TR/audiobooks/#security-privacy

Not sure we should bring up "origin" without defining it, and not sure we should bring it up unless we plan to describe how (or if/when) UA's would be required to implement the [Same-origin Policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy)--which is currently restricted to how desktop/mobile user-focused browsers work, and not often used as a constraint when dealing with APIs (which lean on other mechanisms of restriction).

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-09-16-pwg#section10).

- `RESOLVED:  Close Audiobooks Issue #22, remove the line from the specification and defer to more qualified groups.`
- `ACTION:  edit Audiobooks standard to remove line about the origin. (Wendy Reid)`
<details><summary><i class="differentiate">View the transcript</i></summary>
Wendy Reid: <a href="https://github.com/w3c/audiobooks/issues/22">https://github.com/w3c/audiobooks/issues/22</a><br/>
Ralph Swick: [“be moved to” as in “raised as an issue for discussion in”]<br/>
Wendy Reid: there’s a mention of origin in the privacy and security section of audiobook<br/>
… (quoting from spec about where resources should be same-origin)<br/>
Benjamin Young: given what we just said about pub manifest<br/>
… mentioning it here is confusing<br/>
… we should take it out, or talk about how to handle a manifest<br/>
… so we should just delete the line<br/>
Wendy Reid: I’m happy to delete<br/>
Proposed resolution: Close Audiobooks Issue #22, remove the line from the specification and defer to more qualified groups. (Wendy Reid)<br/>
Benjamin Young: +1<br/>
Charles LaPierre: +1<br/>
Wendy Reid: +1<br/>
Brady Duga: +1<br/>
Benjamin Young: i want to add that there’s something we could call out<br/>
… that’s the use of base in @context<br/>
… you can say there’s a base of all the URLs in the JSON<br/>
… we could have a section that explains how to do that<br/>
… the advantage of @base in context is that your resource list uses fewer bytes<br/>
Resolution #6: Close Audiobooks Issue #22, remove the line from the specification and defer to more qualified groups.<br/>
Action #1: edit Audiobooks standard to remove line about the origin. (Wendy Reid)<br/>
</details>
