### ISSUE TITLE
bounds of an audiobook

### ISSUE THREAD

**Issue by dauwhe** [w3c/audiobooks#26]
The concept of bounds appears to have been removed from the pub manifest spec, but it's the first thing in the audiobook spec. It's also defined in passing in the packaging spec.

How might we better explain why this concept is here? I naively think it might describe those resources to which the metadata applies. Does this conflict with how JSON-LD and schema work?

**Comment by mattgarrish** [comment]
> The concept of bounds appears to have been removed from the pub manifest spec

Largely because it was confined to the web publications section. I think some of the introductory bits can be sliced and diced and integrated back into pub manifest to at least give some foreknowledge of the bounds. (Without the web aspect, though, the bounds of a publication probably isn't quite as fascinating as it was, sadly.)

**Comment by laudrain** [comment]
@mattgarrish Nevertheless, the bounds of a publication are still existing...

**Comment by dauwhe** [comment]
The spec says,

> To determine whether a resource is within the bounds of an Audiobook, user agents MUST compare the absolute URL of a resource to the absolute URLs of the resources obtained from the union. If the resource is identified in the enumeration, it is within the bounds of the Audiobook. All other resources are external to the Audiobook.

How do I write a test for this? How is the user agent going to be aware of a resource that is not in either list? I think of the fundamental idea of the audiobook is that it plays the audio resources in readingOrder, well, in sequence. Are user agents supposed to search nearby servers for audio files just so they can compare their URLs to the URLs in the resource list? And once a user agent identifies a resource outside the bounds of the publication, what does it do? Send an email to the PWG chairs?

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-10-21-pwg#section1-3).

- `RESOLVED:  remove the concept of bounds (2.1.1.) from the audiobooks spec and edit 2.1.3 to fix the reference to publication bounds`
<details><summary><i class="differentiate">View the transcript</i></summary>
bounds of an audiobook #26<br/>
Matt Garrish: <a href="https://github.com/w3c/audiobooks/issues/26">https://github.com/w3c/audiobooks/issues/26</a><br/>
Matt Garrish: next issue, 26, from audiobooks repository, opened by dauwhe<br/>
… . when we split apart pub manifest from audiobook, we don’t talk about bounds… the question is, is there more that we should say in the audiobook specification?<br/>
Dave Cramer: in the context of audiobooks, this seems kind of strange… how is the user agent going to be encountering audio resources that are not in the reading order or other resources?<br/>
… we’re essentially talking about a JSON with a list of things… and user agents are obliged to compare absolute URLs… i’m struggling to be able to test this to see what the goal of this section is… how it influences the behavior of audiobook readers/makers<br/>
… i’m not sure we need the whole section about bounds that we then don’t do anything with<br/>
Matt Garrish: i agree… bounds lose some of the interest when talking about packages, for example<br/>
… regardless of how interesting it is, a publication still have some bounds to it…<br/>
Dave Cramer: i just don’t see how the concept is useful… audiobooks are things, creations of humans, but those aren’t testable and don’t have impact on users or content creators… why have such a prominent position on the spec?<br/>
Matt Garrish: maybe the prominence is misplaced<br/>
George Kerscher: when there is a TOC present, it would seem that the TOC would be required to be restricted to the set of audio files that are being referenced… in that sense, the TOC would be bound to what’s there<br/>
Dave Cramer: that’s a restriction on the TOC, and i could see a TOC with appendices external to the publication’s bounds as we’re describing it here… forbidding that seems a bridge too far<br/>
Benjamin Young: bounds of publication only matter when we’re binding it, so it makes more sense in the context of web publications… what the UA would load or not load… the audiobooks corollary would maybe be packaging… a UA would gather all the pieces and bind it into some machinery… it needs to know what to put in the box<br/>
… with a web publication manifest, we’re learning things dynamically from HTML file, etc., whereas audiobooks are more static, a viewer viewing an audiobook who wants to sandbox it, is going to avoid anything not in the manifest…<br/>
Ivan Herman: trying to remember… the bounds, currently, are defined in publication manifest or audiobooks?<br/>
Benjamin Young: See Reference to bounds in audiobooks<br/>
Benjamin Young: and less-so in pub-manifest<br/>
Matt Garrish: the question seems to be about whether it needs to be a prominent statement, stated at all?<br/>
Ivan Herman: regardless of the contents, if we have it in pub manifest in the general contents, maybe we don’t include it in audiobooks because it’s built on pub manifest anyway<br/>
… I would be in favor of removing from audiobooks and making it a reference, but not defining something like this, which would be a recipe for problems<br/>
… in leaving it in pub manifest, it may serve as the basis for other things later, it may come up<br/>
Matt Garrish: it’s just a definition in pub manifest, and some sentences explaining bounds in the context of web publications, just explaining the concept<br/>
Brady Duga: it does seem like bounds have an implication outside of TOCs, in audiobooks, because supplemental materials could point at other things on the web… so understanding what bounds means would be useful<br/>
Dave Cramer: duga, you’re saying that supplemental content could link to some audio element, and the question would be in what context the UA would play that audio file?<br/>
Brady Duga: could be a link to anything, HTML, wikipedia…<br/>
Dave Cramer: if we’re making the distinction, we’re saying UA should treat some content differently from others… what different thing is supposed to happen if it’s in the bounds or not<br/>
… trying to find out what actionable information is there for the UA for us to put it as the first normative concept in the audiobooks spec<br/>
Benjamin Young: this pivots on whether we define binding… digitally saying what is in bounds, what to load or not load… i only have that list of resources and lock out anything outside of that, or not… it would depend on the code i wrote… so we could do it non-normatively, to give back story or explanation to explain what we mean<br/>
Ivan Herman: i don’t know how we would test it, but my explanation would be a negative explanation… a UA might ignore a resource that is not in its bounds… it MAY ignore that because, e.g., if it goes offline, that document should not be required as part of the user experience… it makes sense to me to know that, and the UA knows what to include in the package…<br/>
… we’re at a point where we’re not bound normatively to a package right now, but at least this gives you a way to ignore things<br/>
Deborah Kaplan: what we’re doing has changed a lot since the last time we had this conversation… we can include it without a plan to use it right now… it’s not so much “is this wiki page essential” but rather “is this font essential?” is it ok if they’re not available, are being blocked, etc.<br/>
Ivan Herman: +1 to dkaplan3<br/>
Deborah Kaplan: . if we have a google analytics script, is it ok if we can’t reach it? is the essential document not there? we were thinking about all the parts of a publication that are not essential to reading it…. some polyfills might be essential… some are just going to be things like fonts and CSS that we can function without… that seemed to be what we were talking about<br/>
Brady Duga: agree with dkaplan3, I think that’s why we did it… but i also agree with dauwhe and bigbluehat… we’ve essentially created a label, but it doesn’t tell me what i need to know if it should be part of the publication or not…<br/>
Dave Cramer: what duga said… if there was some action here… a UA finds out something isn’t in the bounds, what it should do… what action should result from it? just talking about audiobooks spec<br/>
Deborah Kaplan: here’s an action… if you make a test for accessing pages within the bounds, ask if everything within the bounds is something that can be reached by publication navigation?<br/>
… we can write an automated test where this matters, but we are not defining requirements for reading systems as part of this…<br/>
… i don’t think this would be a requirement, but it would be available for a reading system<br/>
… the reading system can decide… and that is a MAY, not a SHOULD or MUST<br/>
… for the reading system—can you test to see if everything in the bounds is reachable? yes, you can<br/>
Ivan Herman: we discuss bounds only in non-normative sections, we define a term and give a general statement about it… i don’t know what the status is in audiobooks, but i have the impression that we have a consensus to remove it from audiobooks spec<br/>
Matt Garrish: seems like this is where the discussion is going… it’s not of NO value, but we don’t need a section… don’t think it’s a critical part of the spec… do we remove it or do we try to rewrite it?<br/>
Ivan Herman: it<br/>
… it’s not a SHOULD/MUST part of the specification<br/>
Dave Cramer: To determine whether a resource is within the bounds of an Audiobook, user agents MUST compare the absolute URL of a resource to the absolute URLs of the resources obtained from the union. If the resource is identified in the enumeration, it is within the bounds of the Audiobook. All other resources are external to the Audiobook.<br/>
Ivan Herman: having that term as a required term in audiobooks? we should remove that.<br/>
Matt Garrish: ok with just removing the section about bounds, 2.1?<br/>
Brady Duga: that’s fine, but 2.1.3, referencing it in a normative section, will have to change… particularly if in pub manifest it’s not a normative term.<br/>
Ivan Herman: we can create an action for the editor to take a closer look<br/>
Brady Duga: in pub manifest, it’s not in a normative section<br/>
Matt Garrish: terminology is normative, no?<br/>
Ivan Herman: not sure<br/>
… what’s the proposal?<br/>
Matt Garrish: to remove section 2.1, make edits to 2.1.3 to fix the references to publication bounds<br/>
Proposed resolution: remove the concept of bounds (2.1.1.) from the audiobooks spec and edit 2.1.3 to fix the reference to publication bounds (Ivan Herman)<br/>
Ivan Herman: +1<br/>
Matt Garrish: +1<br/>
Deborah Kaplan: +0<br/>
Benjamin Young: +1<br/>
Geoff Jukes: +1<br/>
Mateus Teixeira: +1<br/>
Brady Duga: +1<br/>
Dave Cramer: +1<br/>
Resolution #4: remove the concept of bounds (2.1.1.) from the audiobooks spec and edit 2.1.3 to fix the reference to publication bounds<br/>
Ivan Herman: let’s create an action for wendyreid?<br/>
Matt Garrish: she’s on vacation, we may have to figure it out<br/>
… i think we can handle it without her<br/>
Ivan Herman: we cannot move towards CR until all the editing is done… and that one should be done as well<br/>
… we cannot do a final version until the editor is back<br/>
… even if we do the edit, we need an approval from her<br/>
</details>

**Comment by mattgarrish** [comment]
I'm starting to think instead of just dropping this might be useful to transfer up to pub manifest, perhaps more along the lines of a "Publication Resources" section. If we drop, then we don't specifically detail what the complete set of publication resources is supposed to be, which seems like a bad thing to just leave under-specified.

We can also detail quite trivially now that we have the processing algorithm how to extract the union of resources, since the internal representation has already done the hard work of making the URLs absolute and weeding out the invalid ones. It's just another mini-function.

There may not be any specific "musts" in terms of using the information, but going back in time to when we were looking at packaging and offlining as complementary to web publications, there's still potential usefulness in having the information readily available.

Audio books doesn't need to retain 2.1.1, but making this change might help in terms of having a normative way of replacing the reference in 2.1.3
